# Generated by Django 2.0.4 on 2018-05-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostOnTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='604717105:AAGTQje5wWDWXlaJGHy-uylS4WtANe19CjQ', editable=False, max_length=100)),
                ('chat_id', models.CharField(default='@online_shop_saeed', editable=False, max_length=100)),
            ],
        ),
    ]
