# Generated by Django 2.0.4 on 2018-05-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_posting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostOnTelegram',
        ),
    ]
