# Generated by Django 2.0.4 on 2018-05-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180518_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_telegram',
            field=models.BooleanField(default=True),
        ),
    ]
