# Generated by Django 2.0.4 on 2018-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_text_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text_info',
            field=models.TextField(blank=True, max_length=2047),
        ),
    ]
