# Generated by Django 2.0.4 on 2018-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180416_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text_info',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
