# Generated by Django 2.0.4 on 2018-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180417_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_baskets', to='products.Product'),
        ),
    ]
